quota maildir {
    quota_storage_grace = 100M
}

service quota-status {
    quota_status_success = OK
    quota_status_nouser = "REJECT Unknown user"
    quota_status_overquota = "522 5.2.2 Mailbox is full"
    
    executable = quota-status -p postfix
    inet_listener quota-status {
        port = 12340
    }
}