## imap / sieve / imap-sieve migration
#
# Dovecot documentation
# https://doc.dovecot.org/2.4.5/core/plugins/imap_sieve.html
#
# Dovecot Migration to 2.4.5 references
# https://thomas-leister.de/en/mailserver-migrate-config-to-dovecot-2.4-debian-trixie/
# 
# imapsieve structure references / code author (translated for Dovecot 2.4.5)
# https://github.com/mail-in-a-box/mailinabox/pull/2571/changes
# https://github.com/yeah
#

sieve_plugins {
    sieve_imapsieve = yes
	sieve_extprograms = yes
}
sieve_script spam-global {
    type = before
    path = /etc/dovecot/sieve-spam.sieve
}
sieve_script spam-global-before {
    type = before
    path = $STORAGE_ROOT/mail/sieve/global_before
}
sieve_script spam-global-after {
    type = after
    path = $STORAGE_ROOT/mail/sieve/global_after
}
sieve_script personal {
    type = personal
    path = $STORAGE_ROOT/mail/sieve/%{user | domain }/%{user | username }
    active_path = $STORAGE_ROOT/mail/sieve/%{user | domain }/%{user | username }.sieve
    sieve_redirect_envelope_from = recipient
}
sieve_global_extensions {
    vnd.dovecot.pipe = yes
	vnd.dovecot.environment = yes
}

sieve_pipe_bin_dir = /usr/lib/dovecot/sieve

#
## Move Script Blocks
#
#

# From Mailbox to Spam
mailbox Spam {
	sieve_script spam {
		type = before
		cause = copy append
		path = /usr/lib/dovecot/sieve/report-spam.sieve
	}
}
mailbox Junk {
	sieve_script junk {
		type = before
		cause = copy append
		path = /usr/lib/dovecot/sieve/report-spam.sieve
	}
}
imapsieve_from Spam {
	sieve_script ham {
		type = before
		cause = copy
		path = /usr/lib/dovecot/sieve/report-ham.sieve
	}
}
imapsieve_from Junk {
	sieve_script ham {
		type = before
		cause = copy
		path = /usr/lib/dovecot/sieve/report-ham.sieve
	}
}
