#!/bin/bash
curl http://www.okean.com/antispam/iptables/rc.firewall.sinokorea > /tmp/sinokorea.sh
chmod +x /tmp/sinokorea.sh
source /tmp/sinokorea.sh
rm -f /tmp/sinokorea.sh
ipset save > /etc/ipset.up.rules
iptables-save > /etc/iptables.up.rules
