#!/bin/bash
rm -f /etc/nginx/conf.d/local.conf
curl -s -d POSTDATA --user $(</var/lib/mailinabox/api.key): http://127.0.0.1:10222/web/update
cd /etc/nginx/sites-available
for f in miab_*
do
 if ! [ -f "/etc/nginx/sites-enabled/$f" ]; then
  echo "Processing $f"
  ln -s "/etc/nginx/sites-available/$f" "/etc/nginx/sites-enabled/$f"
 fi
done
curl -s -d POSTDATA --user $(</var/lib/mailinabox/api.key): http://127.0.0.1:10222/web/update
